---
- name: BIG-IP SETUP
  hosts: all
  connection: local
  gather_facts: false

  vars:
    provider:
      password: asdfasdfasdf
      server: "{{f5appliance}}"
      server_port: 443
      user: admin
      validate_certs: no

  tasks:
    - name: Create a partition
      bigip_partition: 
        provider: "{{ provider }}"
        name: "{{application_name}}"

    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: least-connections-member
        name: "{{application_name}}_pool"
        partition: "{{application_name}}"
        slow_ramp_time: 120
      delegate_to: localhost

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: 
        destination: "{{Virtual_Server_IP}}"
        name: "{{application_name}}"
        partition: "{{application_name}}"
        port: "{{Virtual_Server_Port}}"
        pool: "{{application_name}}_pool"
        snat: Automap
        default_persistence_profile: /Common/cookie
        fallback_persistence_profile: /Common/source_addr
        profiles:
          - http
          - f5-tcp-progressive
          - oneconnect
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        partition: "{{application_name}}"
        pool: "{{application_name}}_pool"
        port: "{{server_port}}"
      with_items:
        - host: "{{server1ip}}"
          name: "Server_1"
        - host: "{{server2ip}}"
          name: "Server_2"
      delegate_to: localhost
