---
- name: Remove VIP, pool, pool members and nodes
  hosts: all
  connection: local
  vars:
    provider:
      password: asdfasdfasdf
      server: "{{f5appliance}}"
      server_port: 443
      user: admin
      validate_certs: no
  tasks:
    - name: Destroy a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        partition: "{{application_name}}"
        name: "{{application_name}}"
        state: absent
      delegate_to: localhost
    - name: Destroy a pool
      bigip_pool:
        provider: "{{ provider }}"
        partition: "{{application_name}}"
        name: "{{application_name}}_pool"
        state: absent
      delegate_to: localhost
    - name: Delete nodes
      bigip_node:
        provider: "{{ provider }}"
        partition: "{{application_name}}"
        name: "{{ item }}"
        state: absent
      loop:
        - Server_1
        - Server_2
      delegate_to: localhost
    - name: Delete Partition
      bigip_partition:
        provider: "{{ provider }}"
        name: "{{application_name}}"
        state: absent
      delegate_to: localhost
